version: 1
services:
  - type: web
    name: my-flask-app
    env: python
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "python backend/app.py"
    envVars:
      - key: FLASK_ENV
        value: development
